// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $index from "./routes/index.tsx";
import * as $movies_id_ from "./routes/movies/[id].tsx";
import * as $movies_id_comments from "./routes/movies/[id]/comments.tsx";
import * as $movies_middleware from "./routes/movies/_middleware.ts";
import * as $movies_index from "./routes/movies/index.tsx";
import * as $rate_a_movie from "./routes/rate-a-movie.tsx";
import * as $Counter from "./islands/Counter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/joke.ts": $api_joke,
    "./routes/index.tsx": $index,
    "./routes/movies/[id].tsx": $movies_id_,
    "./routes/movies/[id]/comments.tsx": $movies_id_comments,
    "./routes/movies/_middleware.ts": $movies_middleware,
    "./routes/movies/index.tsx": $movies_index,
    "./routes/rate-a-movie.tsx": $rate_a_movie,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
